export const sampleCategories = [
  {
    name: 'Programming',
    slug: 'programming',
    description: 'Master web development, system architecture, algorithms & modern software engineering.',
    icon: '💻',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop',
    bookCount: 8
  },
  {
    name: 'Novels',
    slug: 'novels',
    description: 'Immerse yourself in world-class fiction, romance, thrillers, and award-winning literary works.',
    icon: '📖',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Academic',
    slug: 'academic',
    description: 'Essential textbooks, reference guides, research papers, and scholarly volumes.',
    icon: '🎓',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Children',
    slug: 'children',
    description: 'Delightful picture books, bed-time fairy tales, and engaging early reader adventures.',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Fantasy',
    slug: 'fantasy',
    description: 'Epic worlds, mythical creatures, high magic, and breathtaking heroic sagas.',
    icon: '🐉',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Biography',
    slug: 'biography',
    description: 'Inspiring life stories of visionaries, pioneers, leaders, and legendary figures.',
    icon: '👤',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'History',
    slug: 'history',
    description: 'Explore pivotal moments, ancient civilizations, world wars, and human heritage.',
    icon: '🏛️',
    image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop',
    bookCount: 4
  },
  {
    name: 'Science',
    slug: 'science',
    description: 'Discover quantum physics, astronomy, genetics, climate science, and nature.',
    icon: '🔬',
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Self Help',
    slug: 'self-help',
    description: 'Actionable strategies for personal transformation, productivity, mindsets & success.',
    icon: '🌱',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Mystery',
    slug: 'mystery',
    description: 'Gripping detective crime thrillers, unanswerable enigmas, and psychological suspense.',
    icon: '🔍',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop',
    bookCount: 5
  }
];

export const sampleBooks = [
  {
    _id: 'sample-1',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    price: 39.99,
    originalPrice: 49.99,
    discountPercent: 20,
    category: 'Programming',
    description: 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code.',
    stock: 25,
    coverImage: "/images/cleancode.png",
    publisher: 'Prentice Hall',
    isbn: '978-0132350884',
    language: 'English',
    rating: 4.8,
    numReviews: 142,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-2',
    title: 'JavaScript: The Definitive Guide (7th Edition)',
    author: 'David Flanagan',
    price: 44.50,
    originalPrice: 59.99,
    discountPercent: 25,
    category: 'Programming',
    description: 'JavaScript is the programming language of the web and is used by more software developers than any other programming language. Comprehensive guide for modern developers.',
    stock: 18,
    coverImage: '/images/js.png',
    publisher: "O'Reilly Media",
    isbn: '978-1491952023',
    language: 'English',
    rating: 4.7,
    numReviews: 98,
    isFeatured: true,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    _id: 'sample-3',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    price: 49.99,
    originalPrice: 64.99,
    discountPercent: 23,
    category: 'Programming',
    description: 'Data is at the center of many challenges in system design today. Learn key principles behind distributed systems, databases, and reliability.',
    stock: 14,
    coverImage: '/images/designing.png',
    publisher: "O'Reilly Media",
    isbn: '978-1449373320',
    language: 'English',
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-4',
    title: 'Full Stack React Projects (Modern Web Apps)',
    author: 'Shama Hoque',
    price: 34.99,
    originalPrice: 42.00,
    discountPercent: 16,
    category: 'Programming',
    description: 'Build full-stack web applications with modern React, Express, Node.js, and MongoDB. Practical hands-on examples for real-world production projects.',
    stock: 30,
    coverImage: '/images/react.png',
    publisher: 'Packt Publishing',
    isbn: '978-1839215421',
    language: 'English',
    rating: 4.6,
    numReviews: 54,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
  },
  {
    _id: 'sample-5',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 14.99,
    originalPrice: 19.99,
    discountPercent: 25,
    category: 'Novels',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. Set in Jazz Age Long Island, it is a supreme classic of American literature.',
    stock: 40,
    coverImage: '/images/great_gats.png',
    publisher: 'Scribner',
    isbn: '978-0743273565',
    language: 'English',
    rating: 4.6,
    numReviews: 320,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-6',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 16.50,
    originalPrice: 21.00,
    discountPercent: 21,
    category: 'Novels',
    description: 'Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty.',
    stock: 35,
    coverImage: '/images/mockingbird.png',
    publisher: 'HarperPerennial',
    isbn: '978-0060935467',
    language: 'English',
    rating: 4.9,
    numReviews: 450,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-7',
    title: 'Principles of Physics (11th Edition)',
    author: 'David Halliday & Robert Resnick',
    price: 89.99,
    originalPrice: 110.00,
    discountPercent: 18,
    category: 'Academic',
    description: 'The golden standard textbook for university physics. Covers mechanics, thermodynamics, electromagnetism, optics, and modern physics.',
    stock: 12,
    coverImage: '/images/physics.png',
    publisher: 'Wiley',
    isbn: '978-1119454014',
    language: 'English',
    rating: 4.7,
    numReviews: 76,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    _id: 'sample-8',
    title: 'The Secret Garden & Magical Adventures',
    author: 'Frances Hodgson Burnett',
    price: 12.99,
    originalPrice: 15.99,
    discountPercent: 18,
    category: 'Children',
    description: 'An enchanting tale of young Mary Lennox who discovers a hidden, neglected garden and unlocks magic, friendship, and joy.',
    stock: 50,
    coverImage: '/images/secretegarden.png',
    publisher: 'Puffin Books',
    isbn: '978-0141321066',
    language: 'English',
    rating: 4.9,
    numReviews: 180,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-9',
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits',
    author: 'James Clear',
    price: 19.99,
    originalPrice: 27.00,
    discountPercent: 26,
    category: 'Self Help',
    description: 'Atomic Habits offers a proven framework for improving every day. Practical strategies for habit formation and productivity.',
    stock: 45,
    coverImage: '/images/atomichabits.png',
    publisher: 'Avery',
    isbn: '978-0735211292',
    language: 'English',
    rating: 4.9,
    numReviews: 890,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-10',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 17.99,
    originalPrice: 24.99,
    discountPercent: 28,
    category: 'Mystery',
    description: 'A shocking psychological thriller about a woman\'s act of violence against her husband, and the therapist obsessed with uncovering her motive.',
    stock: 25,
    coverImage: '/images/silentpatient.png',
    publisher: 'Celadon Books',
    isbn: '978-1250301697',
    language: 'English',
    rating: 4.7,
    numReviews: 380,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-11',
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J. K. Rowling',
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: 17,
    category: 'Fantasy',
    description: 'A young wizard discovers his magical heritage and begins his journey at Hogwarts.',
    stock: 30,
    coverImage: '/images/harrypotter.png',
    publisher: 'Bloomsbury',
    isbn: '9780747532699',
    language: 'English',
    rating: 4.9,
    numReviews: 1200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-12',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: 17,
    category: 'Biography',
    description: 'The official biography of Apple co-founder Steve Jobs.',
    stock: 20,
    coverImage: '/images/stevejobs.png',
    publisher: 'Simon & Schuster',
    isbn: '9781451648539',
    language: 'English',
    rating: 4.8,
    numReviews: 1250,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-13',
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    price: 19.99,
    originalPrice: 25.99,
    discountPercent: 23,
    category: 'Biography',
    description: 'Autobiography of Nelson Mandela.',
    stock: 18,
    coverImage: '/images/nelsonmandela.png',
    publisher: 'Little, Brown',
    isbn: '9780316548182',
    language: 'English',
    rating: 4.9,
    numReviews: 980,
    isFeatured: false,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-14',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    price: 21.99,
    originalPrice: 27.99,
    discountPercent: 21,
    category: 'History',
    description: 'A brief history of humankind.',
    stock: 22,
    coverImage: '/images/sapiens.png',
    publisher: 'Harper',
    isbn: '9780062316097',
    language: 'English',
    rating: 4.8,
    numReviews: 2100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-15',
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    price: 23.99,
    originalPrice: 30.99,
    discountPercent: 22,
    category: 'History',
    description: 'Explains how geography shaped human civilizations.',
    stock: 15,
    coverImage: '/images/national.png',
    publisher: 'W. W. Norton',
    isbn: '9780393317558',
    language: 'English',
    rating: 4.7,
    numReviews: 850,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
},
{
    _id: 'sample-16',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    price: 18.99,
    originalPrice: 24.99,
    discountPercent: 24,
    category: 'Science',
    description: 'An introduction to cosmology and black holes.',
    stock: 30,
    coverImage: '/images/stephen.png',
    publisher: 'Bantam Books',
    isbn: '9780553380163',
    language: 'English',
    rating: 4.8,
    numReviews: 3100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-17',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    price: 20.99,
    originalPrice: 26.99,
    discountPercent: 22,
    category: 'Science',
    description: 'A classic work on evolution and genetics.',
    stock: 17,
    coverImage: '/images/selfish.png',
    publisher: 'Oxford University Press',
    isbn: '9780199291151',
    language: 'English',
    rating: 4.7,
    numReviews: 920,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
},
{
    _id: 'sample-18',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    price: 19.99,
    originalPrice: 24.99,
    discountPercent: 20,
    category: 'Novels',
    description: 'A timeless classic exploring love, family, and social expectations in 19th-century England.',
    stock: 30,
    coverImage: '/images/prejudice.png',
    publisher: 'Penguin Classics',
    isbn: '9780141439518',
    language: 'English',
    rating: 4.8,
    numReviews: 1850,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-21',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    price: 20.99,
    originalPrice: 26.99,
    discountPercent: 22,
    category: 'Novels',
    description: 'A thought-provoking novel about choices, regrets, and finding meaning in life.',
    stock: 32,
    coverImage: '/images/Midnight.png',
    publisher: 'Canongate Books',
    isbn: '9781786892737',
    language: 'English',
    rating: 4.7,
    numReviews: 11500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-20',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    price: 22.99,
    originalPrice: 28.99,
    discountPercent: 21,
    category: 'Novels',
    description: 'A mystery and coming-of-age novel set in the North Carolina marshlands.',
    stock: 28,
    coverImage: '/images/where.png',
    publisher: 'G.P. Putnam\'s Sons',
    isbn: '9780735219090',
    language: 'English',
    rating: 4.8,
    numReviews: 9800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-21',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 17.99,
    originalPrice: 22.99,
    discountPercent: 22,
    category: 'Novels',
    description: 'An inspiring story about following dreams and discovering one’s personal legend.',
    stock: 35,
    coverImage: '/images/o.png',
    publisher: 'HarperOne',
    isbn: '9780061122415',
    language: 'English',
    rating: 4.8,
    numReviews: 5200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-22',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    price: 49.99,
    originalPrice: 59.99,
    discountPercent: 17,
    category: 'Academic',
    description: 'A comprehensive textbook covering algorithms, data structures, and computational problem solving.',
    stock: 20,
    coverImage: '/images/algorithm.png',
    publisher: 'MIT Press',
    isbn: '9780262046305',
    language: 'English',
    rating: 4.9,
    numReviews: 3500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-23',
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    price: 44.99,
    originalPrice: 54.99,
    discountPercent: 18,
    category: 'Academic',
    description: 'An in-depth guide to database systems, SQL, normalization, and transaction management.',
    stock: 18,
    coverImage: '/images/daatabase.png',
    publisher: 'McGraw-Hill',
    isbn: '9780078022159',
    language: 'English',
    rating: 4.8,
    numReviews: 2800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-24',
    title: 'Operating System Concepts',
    author: 'Abraham Silberschatz',
    price: 46.99,
    originalPrice: 56.99,
    discountPercent: 18,
    category: 'Academic',
    description: 'A widely used textbook covering operating systems, process management, memory management, and file systems.',
    stock: 22,
    coverImage: '/images/os.png',
    publisher: 'Wiley',
    isbn: '9781119800361',
    language: 'English',
    rating: 4.8,
    numReviews: 3100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-25',
    title: 'Discrete Mathematics and Its Applications',
    author: 'Kenneth H. Rosen',
    price: 42.99,
    originalPrice: 52.99,
    discountPercent: 19,
    category: 'Academic',
    description: 'An essential textbook covering logic, sets, combinatorics, graph theory, and discrete structures.',
    stock: 24,
    coverImage: '/images/discretemaths.png',
    publisher: 'McGraw-Hill',
    isbn: '9781259676512',
    language: 'English',
    rating: 4.7,
    numReviews: 2400,
    isFeatured: false,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-26',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell & Peter Norvig',
    price: 54.99,
    originalPrice: 64.99,
    discountPercent: 15,
    category: 'Academic',
    description: 'A leading textbook introducing artificial intelligence, machine learning, search algorithms, and intelligent agents.',
    stock: 15,
    coverImage: '/images/ai.png',
    publisher: 'Pearson',
    isbn: '9780134610993',
    language: 'English',
    rating: 4.9,
    numReviews: 4200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-27',
    title: 'The Very Hungry Caterpillar',
    author: 'Eric Carle',
    price: 14.99,
    originalPrice: 19.99,
    discountPercent: 25,
    category: 'Children',
    description: 'A beloved picture book that follows the journey of a hungry caterpillar as it grows into a beautiful butterfly.',
    stock: 40,
    coverImage: '/images/catterpiller.png',
    publisher: 'World Publishing Company',
    isbn: '9780399226908',
    language: 'English',
    rating: 4.9,
    numReviews: 8500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-28',
    title: 'Charlotte\'s Web',
    author: 'E. B. White',
    price: 16.99,
    originalPrice: 21.99,
    discountPercent: 23,
    category: 'Children',
    description: 'A heartwarming story of friendship between a pig named Wilbur and a spider named Charlotte.',
    stock: 35,
    coverImage: '/images/web.png',
    publisher: 'HarperCollins',
    isbn: '9780064400558',
    language: 'English',
    rating: 4.8,
    numReviews: 7200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-29',
    title: 'Matilda',
    author: 'Roald Dahl',
    price: 18.99,
    originalPrice: 23.99,
    discountPercent: 21,
    category: 'Children',
    description: 'An inspiring story of a brilliant little girl with extraordinary abilities and a love for books.',
    stock: 30,
    coverImage: '/images/matilda.png',
    publisher: 'Puffin Books',
    isbn: '9780142410370',
    language: 'English',
    rating: 4.8,
    numReviews: 6800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-30',
    title: 'The Gruffalo',
    author: 'Julia Donaldson',
    price: 15.99,
    originalPrice: 20.99,
    discountPercent: 24,
    category: 'Children',
    description: 'A delightful rhyming story about a clever mouse who outsmarts predators in the forest.',
    stock: 38,
    coverImage: '/images/gruffalo.png',
    publisher: 'Macmillan Children\'s Books',
    isbn: '9781509830390',
    language: 'English',
    rating: 4.9,
    numReviews: 7900,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-31',
    title: 'The Cat in the Hat',
    author: 'Dr. Seuss',
    price: 13.99,
    originalPrice: 18.99,
    discountPercent: 26,
    category: 'Children',
    description: 'A fun-filled classic featuring the mischievous Cat in the Hat and his unforgettable adventures.',
    stock: 45,
    coverImage: '/images/cat.png',
    publisher: 'Random House',
    isbn: '9780394800011',
    language: 'English',
    rating: 4.8,
    numReviews: 9100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-32',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: 17,
    category: 'Fantasy',
    description: 'A timeless fantasy adventure following Bilbo Baggins on an unexpected journey filled with dragons, dwarves, and treasure.',
    stock: 30,
    coverImage: '/images/hobbit.png',
    publisher: 'HarperCollins',
    isbn: '9780261102217',
    language: 'English',
    rating: 4.9,
    numReviews: 9800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-33',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    price: 39.99,
    originalPrice: 49.99,
    discountPercent: 20,
    category: 'Fantasy',
    description: 'An epic fantasy trilogy that follows Frodo Baggins on his quest to destroy the One Ring.',
    stock: 25,
    coverImage: '/images/lord.png',
    publisher: 'HarperCollins',
    isbn: '9780261102385',
    language: 'English',
    rating: 4.9,
    numReviews: 14500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-34',
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    price: 29.99,
    originalPrice: 36.99,
    discountPercent: 19,
    category: 'Fantasy',
    description: 'A magical journey through the land of Narnia where children encounter talking animals and legendary heroes.',
    stock: 28,
    coverImage: '/images/narnia.png',
    publisher: 'HarperCollins',
    isbn: '9780066238500',
    language: 'English',
    rating: 4.8,
    numReviews: 9200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-35',
    title: 'Eragon',
    author: 'Christopher Paolini',
    price: 23.99,
    originalPrice: 29.99,
    discountPercent: 20,
    category: 'Fantasy',
    description: 'A young farm boy discovers a dragon egg and becomes a Dragon Rider in a world of magic and adventure.',
    stock: 26,
    coverImage: '/images/eragon.png',
    publisher: 'Knopf Books',
    isbn: '9780375826689',
    language: 'English',
    rating: 4.7,
    numReviews: 7600,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-36',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    price: 27.99,
    originalPrice: 34.99,
    discountPercent: 20,
    category: 'Fantasy',
    description: 'The captivating story of Kvothe, a gifted young magician whose adventures become legendary.',
    stock: 20,
    coverImage: '/images/thenameofthewind.png',
    publisher: 'DAW Books',
    isbn: '9780756404741',
    language: 'English',
    rating: 4.8,
    numReviews: 8800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-37',
    title: 'Becoming',
    author: 'Michelle Obama',
    price: 26.99,
    originalPrice: 32.99,
    discountPercent: 18,
    category: 'Biography',
    description: 'The inspiring memoir of former First Lady Michelle Obama, sharing her journey from childhood to the White House.',
    stock: 30,
    coverImage: '/images/becoming.png',
    publisher: 'Crown Publishing',
    isbn: '9781524763138',
    language: 'English',
    rating: 4.9,
    numReviews: 14500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-38',
    title: 'Wings of Fire',
    author: 'A.P.J. Abdul Kalam',
    price: 18.99,
    originalPrice: 24.99,
    discountPercent: 24,
    category: 'Biography',
    description: 'The autobiography of Dr. A.P.J. Abdul Kalam, highlighting his journey from a small town to becoming the President of India.',
    stock: 40,
    coverImage: '/images/wingsoffire.png',
    publisher: 'Universities Press',
    isbn: '9788173711466',
    language: 'English',
    rating: 4.9,
    numReviews: 12800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-39',
    title: 'The Diary of a Young Girl',
    author: 'Anne Frank',
    price: 16.99,
    originalPrice: 21.99,
    discountPercent: 23,
    category: 'Biography',
    description: 'Anne Frank’s remarkable diary, documenting her life and experiences during World War II.',
    stock: 28,
    coverImage: '/images/annefrank.png',
    publisher: 'Penguin Books',
    isbn: '9780141036144',
    language: 'English',
    rating: 4.8,
    numReviews: 11200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-40',
    title: 'Einstein: His Life and Universe',
    author: 'Walter Isaacson',
    price: 28.99,
    originalPrice: 35.99,
    discountPercent: 19,
    category: 'Biography',
    description: 'An engaging biography of Albert Einstein, exploring his scientific discoveries and extraordinary life.',
    stock: 22,
    coverImage: '/images/einstein.png',
    publisher: 'Simon & Schuster',
    isbn: '9780743264747',
    language: 'English',
    rating: 4.8,
    numReviews: 7600,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-41',
    title: 'Shoe Dog',
    author: 'Phil Knight',
    price: 23.99,
    originalPrice: 29.99,
    discountPercent: 20,
    category: 'Biography',
    description: 'Nike founder Phil Knight shares the inspiring story behind building one of the world’s most successful companies.',
    stock: 26,
    coverImage: '/images/shoedog.png',
    publisher: 'Scribner',
    isbn: '9781501135910',
    language: 'English',
    rating: 4.8,
    numReviews: 9800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-42',
    title: 'The Silk Roads',
    author: 'Peter Frankopan',
    price: 27.99,
    originalPrice: 34.99,
    discountPercent: 20,
    category: 'History',
    description: 'A fascinating history of the world through the ancient trade routes that connected civilizations.',
    stock: 25,
    coverImage: '/images/silkroads.png',
    publisher: 'Bloomsbury Publishing',
    isbn: '9781408839973',
    language: 'English',
    rating: 4.8,
    numReviews: 6200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-43',
    title: 'The Wright Brothers',
    author: 'David McCullough',
    price: 24.99,
    originalPrice: 30.99,
    discountPercent: 19,
    category: 'History',
    description: 'The inspiring story of Orville and Wilbur Wright and their pioneering achievements in aviation.',
    stock: 22,
    coverImage: '/images/thewrightbrothers.png',
    publisher: 'Simon & Schuster',
    isbn: '9781476728742',
    language: 'English',
    rating: 4.7,
    numReviews: 5100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-44',
    title: 'The Second World War',
    author: 'Antony Beevor',
    price: 32.99,
    originalPrice: 39.99,
    discountPercent: 18,
    category: 'History',
    description: 'A comprehensive account of World War II, covering its major battles, leaders, and global impact.',
    stock: 18,
    coverImage: '/images/thesecondworldwar.png',
    publisher: 'Little, Brown',
    isbn: '9780316023740',
    language: 'English',
    rating: 4.9,
    numReviews: 7300,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-45',
    title: 'SPQR: A History of Ancient Rome',
    author: 'Mary Beard',
    price: 26.99,
    originalPrice: 33.99,
    discountPercent: 21,
    category: 'History',
    description: 'An engaging history of Ancient Rome, from its legendary beginnings to its rise as a global empire.',
    stock: 20,
    coverImage: '/images/spqr.png',
    publisher: 'Liveright Publishing',
    isbn: '9781631492228',
    language: 'English',
    rating: 4.8,
    numReviews: 5900,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-46',
    title: '1776',
    author: 'David McCullough',
    price: 23.99,
    originalPrice: 29.99,
    discountPercent: 20,
    category: 'History',
    description: 'A compelling account of the American Revolutionary War and the leadership of George Washington.',
    stock: 24,
    coverImage: '/images/1776.png',
    publisher: 'Simon & Schuster',
    isbn: '9780743226721',
    language: 'English',
    rating: 4.7,
    numReviews: 6800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-47',
    title: 'Cosmos',
    author: 'Carl Sagan',
    price: 26.99,
    originalPrice: 32.99,
    discountPercent: 18,
    category: 'Science',
    description: 'A fascinating exploration of the universe, astronomy, and humanity’s place in the cosmos.',
    stock: 30,
    coverImage: '/images/cosmos.png',
    publisher: 'Ballantine Books',
    isbn: '9780345539434',
    language: 'English',
    rating: 4.9,
    numReviews: 12500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-48',
    title: 'The Gene: An Intimate History',
    author: 'Siddhartha Mukherjee',
    price: 28.99,
    originalPrice: 35.99,
    discountPercent: 19,
    category: 'Science',
    description: 'An engaging history of genetics, explaining how genes shape life, health, and human evolution.',
    stock: 24,
    coverImage: '/images/thegene.png',
    publisher: 'Scribner',
    isbn: '9781476733524',
    language: 'English',
    rating: 4.8,
    numReviews: 8400,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-49',
    title: 'The Body: A Guide for Occupants',
    author: 'Bill Bryson',
    price: 24.99,
    originalPrice: 30.99,
    discountPercent: 19,
    category: 'Science',
    description: 'A fascinating journey through the human body, explaining how it works in an engaging and accessible way.',
    stock: 28,
    coverImage: '/images/thebody.png',
    publisher: 'Doubleday',
    isbn: '9780385539302',
    language: 'English',
    rating: 4.8,
    numReviews: 7300,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-50',
    title: 'The Immortal Life of Henrietta Lacks',
    author: 'Rebecca Skloot',
    price: 22.99,
    originalPrice: 28.99,
    discountPercent: 21,
    category: 'Science',
    description: 'The remarkable true story of Henrietta Lacks and the immortal cells that transformed modern medicine.',
    stock: 22,
    coverImage: '/images/henriettalacks.png',
    publisher: 'Broadway Books',
    isbn: '9781400052189',
    language: 'English',
    rating: 4.8,
    numReviews: 9100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-51',
    title: 'The Hidden Life of Trees',
    author: 'Peter Wohlleben',
    price: 23.99,
    originalPrice: 29.99,
    discountPercent: 20,
    category: 'Science',
    description: 'A bestselling science book revealing how trees communicate, cooperate, and thrive in forests.',
    stock: 26,
    coverImage: '/images/thehiddenlifeoftrees.png',
    publisher: 'Greystone Books',
    isbn: '9781771642484',
    language: 'English',
    rating: 4.7,
    numReviews: 6800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-52',
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    price: 24.99,
    originalPrice: 30.99,
    discountPercent: 19,
    category: 'Self Help',
    description: 'A timeless guide to personal and professional effectiveness through seven powerful habits.',
    stock: 30,
    coverImage: '/images/7habits.png',
    publisher: 'Free Press',
    isbn: '9781982137274',
    language: 'English',
    rating: 4.9,
    numReviews: 14200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-53',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    price: 22.99,
    originalPrice: 28.99,
    discountPercent: 21,
    category: 'Self Help',
    description: 'A bestselling book that teaches the importance of living in the present moment for inner peace and happiness.',
    stock: 28,
    coverImage: '/images/thepowerofnow.png',
    publisher: 'New World Library',
    isbn: '9781577314806',
    language: 'English',
    rating: 4.8,
    numReviews: 11800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-54',
    title: 'Think Like a Monk',
    author: 'Jay Shetty',
    price: 20.99,
    originalPrice: 26.99,
    discountPercent: 22,
    category: 'Self Help',
    description: 'Jay Shetty shares practical wisdom inspired by his life as a monk to help readers find purpose and peace.',
    stock: 35,
    coverImage: '/images/thinklikeamonk.png',
    publisher: 'Simon & Schuster',
    isbn: '9781982134488',
    language: 'English',
    rating: 4.8,
    numReviews: 10400,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-55',
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    price: 21.99,
    originalPrice: 27.99,
    discountPercent: 21,
    category: 'Self Help',
    description: 'A refreshing approach to living a meaningful life by focusing on what truly matters.',
    stock: 32,
    coverImage: '/images/subtleart.png',
    publisher: 'Harper',
    isbn: '9780062457714',
    language: 'English',
    rating: 4.7,
    numReviews: 16700,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-56',
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Héctor García & Francesc Miralles',
    price: 18.99,
    originalPrice: 24.99,
    discountPercent: 24,
    category: 'Self Help',
    description: 'Discover the Japanese philosophy of finding purpose, happiness, and fulfillment in everyday life.',
    stock: 40,
    coverImage: '/images/ikigai.png',
    publisher: 'Penguin Life',
    isbn: '9780143130727',
    language: 'English',
    rating: 4.8,
    numReviews: 15200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-57',
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    price: 22.99,
    originalPrice: 28.99,
    discountPercent: 21,
    category: 'Mystery',
    description: 'A gripping psychological thriller about a husband who becomes the prime suspect in his wife’s mysterious disappearance.',
    stock: 30,
    coverImage: '/images/gonegirl.png',
    publisher: 'Crown Publishing',
    isbn: '9780307588371',
    language: 'English',
    rating: 4.8,
    numReviews: 13500,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-58',
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    price: 24.99,
    originalPrice: 31.99,
    discountPercent: 22,
    category: 'Mystery',
    description: 'A bestselling mystery novel featuring journalist Mikael Blomkvist and hacker Lisbeth Salander investigating a decades-old disappearance.',
    stock: 26,
    coverImage: '/images/dragontattoo.png',
    publisher: 'Norstedts Förlag',
    isbn: '9780307454546',
    language: 'English',
    rating: 4.8,
    numReviews: 12400,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-59',
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    price: 21.99,
    originalPrice: 27.99,
    discountPercent: 21,
    category: 'Mystery',
    description: 'A fast-paced mystery thriller following symbologist Robert Langdon as he uncovers hidden secrets across Europe.',
    stock: 34,
    coverImage: '/images/davincicode.png',
    publisher: 'Doubleday',
    isbn: '9780385504201',
    language: 'English',
    rating: 4.7,
    numReviews: 18400,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-60',
    title: 'Murder on the Orient Express',
    author: 'Agatha Christie',
    price: 19.99,
    originalPrice: 24.99,
    discountPercent: 20,
    category: 'Mystery',
    description: 'Detective Hercule Poirot investigates a shocking murder aboard the luxurious Orient Express.',
    stock: 32,
    coverImage: '/images/orientexpress.png',
    publisher: 'Collins Crime Club',
    isbn: '9780007119318',
    language: 'English',
    rating: 4.9,
    numReviews: 9800,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-61',
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    price: 20.99,
    originalPrice: 26.99,
    discountPercent: 22,
    category: 'Mystery',
    description: 'Ten strangers are invited to a remote island where they become trapped in a deadly and suspenseful mystery.',
    stock: 28,
    coverImage: '/images/andthentherewerenone.png',
    publisher: 'Collins Crime Club',
    isbn: '9780062073488',
    language: 'English',
    rating: 4.9,
    numReviews: 15200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
];
