export const sampleCategories = [
  {
    name: 'Programming',
    slug: 'programming',
    description: 'Master web development, system architecture, algorithms & modern software engineering.',
    icon: '💻',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop',
    bookCount: 8
  },
  {
    name: 'Novels',
    slug: 'novels',
    description: 'Immerse yourself in world-class fiction, romance, thrillers, and award-winning literary works.',
    icon: '📖',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Academic',
    slug: 'academic',
    description: 'Essential textbooks, reference guides, research papers, and scholarly volumes.',
    icon: '🎓',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Children',
    slug: 'children',
    description: 'Delightful picture books, bed-time fairy tales, and engaging early reader adventures.',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Fantasy',
    slug: 'fantasy',
    description: 'Epic worlds, mythical creatures, high magic, and breathtaking heroic sagas.',
    icon: '🐉',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Biography',
    slug: 'biography',
    description: 'Inspiring life stories of visionaries, pioneers, leaders, and legendary figures.',
    icon: '👤',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'History',
    slug: 'history',
    description: 'Explore pivotal moments, ancient civilizations, world wars, and human heritage.',
    icon: '🏛️',
    image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop',
    bookCount: 4
  },
  {
    name: 'Science',
    slug: 'science',
    description: 'Discover quantum physics, astronomy, genetics, climate science, and nature.',
    icon: '🔬',
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Self Help',
    slug: 'self-help',
    description: 'Actionable strategies for personal transformation, productivity, mindsets & success.',
    icon: '🌱',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Mystery',
    slug: 'mystery',
    description: 'Gripping detective crime thrillers, unanswerable enigmas, and psychological suspense.',
    icon: '🔍',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop',
    bookCount: 5
  }
];

export const sampleBooks = [
  {
    _id: 'sample-1',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    price: 39.99,
    originalPrice: 49.99,
    discountPercent: 20,
    category: 'Programming',
    description: 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code.',
    stock: 25,
    coverImage: "/images/cleancode.png",
    publisher: 'Prentice Hall',
    isbn: '978-0132350884',
    language: 'English',
    rating: 4.8,
    numReviews: 142,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-2',
    title: 'JavaScript: The Definitive Guide (7th Edition)',
    author: 'David Flanagan',
    price: 44.50,
    originalPrice: 59.99,
    discountPercent: 25,
    category: 'Programming',
    description: 'JavaScript is the programming language of the web and is used by more software developers than any other programming language. Comprehensive guide for modern developers.',
    stock: 18,
    coverImage: '/images/js.png',
    publisher: "O'Reilly Media",
    isbn: '978-1491952023',
    language: 'English',
    rating: 4.7,
    numReviews: 98,
    isFeatured: true,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    _id: 'sample-3',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    price: 49.99,
    originalPrice: 64.99,
    discountPercent: 23,
    category: 'Programming',
    description: 'Data is at the center of many challenges in system design today. Learn key principles behind distributed systems, databases, and reliability.',
    stock: 14,
    coverImage: '/images/designing.png',
    publisher: "O'Reilly Media",
    isbn: '978-1449373320',
    language: 'English',
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-4',
    title: 'Full Stack React Projects (Modern Web Apps)',
    author: 'Shama Hoque',
    price: 34.99,
    originalPrice: 42.00,
    discountPercent: 16,
    category: 'Programming',
    description: 'Build full-stack web applications with modern React, Express, Node.js, and MongoDB. Practical hands-on examples for real-world production projects.',
    stock: 30,
    coverImage: '/images/react.png',
    publisher: 'Packt Publishing',
    isbn: '978-1839215421',
    language: 'English',
    rating: 4.6,
    numReviews: 54,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
  },
  {
    _id: 'sample-5',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 14.99,
    originalPrice: 19.99,
    discountPercent: 25,
    category: 'Novels',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. Set in Jazz Age Long Island, it is a supreme classic of American literature.',
    stock: 40,
    coverImage: '/images/great_gats.png',
    publisher: 'Scribner',
    isbn: '978-0743273565',
    language: 'English',
    rating: 4.6,
    numReviews: 320,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-6',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 16.50,
    originalPrice: 21.00,
    discountPercent: 21,
    category: 'Novels',
    description: 'Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty.',
    stock: 35,
    coverImage: '/images/mockingbird.png',
    publisher: 'HarperPerennial',
    isbn: '978-0060935467',
    language: 'English',
    rating: 4.9,
    numReviews: 450,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-7',
    title: 'Principles of Physics (11th Edition)',
    author: 'David Halliday & Robert Resnick',
    price: 89.99,
    originalPrice: 110.00,
    discountPercent: 18,
    category: 'Academic',
    description: 'The golden standard textbook for university physics. Covers mechanics, thermodynamics, electromagnetism, optics, and modern physics.',
    stock: 12,
    coverImage: '/images/physics.png',
    publisher: 'Wiley',
    isbn: '978-1119454014',
    language: 'English',
    rating: 4.7,
    numReviews: 76,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    _id: 'sample-8',
    title: 'The Secret Garden & Magical Adventures',
    author: 'Frances Hodgson Burnett',
    price: 12.99,
    originalPrice: 15.99,
    discountPercent: 18,
    category: 'Children',
    description: 'An enchanting tale of young Mary Lennox who discovers a hidden, neglected garden and unlocks magic, friendship, and joy.',
    stock: 50,
    coverImage: '/images/secretegarden.png',
    publisher: 'Puffin Books',
    isbn: '978-0141321066',
    language: 'English',
    rating: 4.9,
    numReviews: 180,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-9',
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits',
    author: 'James Clear',
    price: 19.99,
    originalPrice: 27.00,
    discountPercent: 26,
    category: 'Self Help',
    description: 'Atomic Habits offers a proven framework for improving every day. Practical strategies for habit formation and productivity.',
    stock: 45,
    coverImage: '/images/atomichabits.png',
    publisher: 'Avery',
    isbn: '978-0735211292',
    language: 'English',
    rating: 4.9,
    numReviews: 890,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    _id: 'sample-10',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 17.99,
    originalPrice: 24.99,
    discountPercent: 28,
    category: 'Mystery',
    description: 'A shocking psychological thriller about a woman\'s act of violence against her husband, and the therapist obsessed with uncovering her motive.',
    stock: 25,
    coverImage: '/images/silentpatient.png',
    publisher: 'Celadon Books',
    isbn: '978-1250301697',
    language: 'English',
    rating: 4.7,
    numReviews: 380,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    _id: 'sample-11',
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J. K. Rowling',
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: 17,
    category: 'Fantasy',
    description: 'A young wizard discovers his magical heritage and begins his journey at Hogwarts.',
    stock: 30,
    coverImage: '/images/harrypotter.png',
    publisher: 'Bloomsbury',
    isbn: '9780747532699',
    language: 'English',
    rating: 4.9,
    numReviews: 1200,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-12',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    price: 24.99,
    originalPrice: 29.99,
    discountPercent: 17,
    category: 'Biography',
    description: 'The official biography of Apple co-founder Steve Jobs.',
    stock: 20,
    coverImage: '/images/stevejobs.png',
    publisher: 'Simon & Schuster',
    isbn: '9781451648539',
    language: 'English',
    rating: 4.8,
    numReviews: 1250,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-13',
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    price: 19.99,
    originalPrice: 25.99,
    discountPercent: 23,
    category: 'Biography',
    description: 'Autobiography of Nelson Mandela.',
    stock: 18,
    coverImage: '/images/nelsonmandela.png',
    publisher: 'Little, Brown',
    isbn: '9780316548182',
    language: 'English',
    rating: 4.9,
    numReviews: 980,
    isFeatured: false,
    isBestSeller: true,
    isTodayOffer: true
},
{
    _id: 'sample-14',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    price: 21.99,
    originalPrice: 27.99,
    discountPercent: 21,
    category: 'History',
    description: 'A brief history of humankind.',
    stock: 22,
    coverImage: '/images/sapiens.png',
    publisher: 'Harper',
    isbn: '9780062316097',
    language: 'English',
    rating: 4.8,
    numReviews: 2100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-15',
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    price: 23.99,
    originalPrice: 30.99,
    discountPercent: 22,
    category: 'History',
    description: 'Explains how geography shaped human civilizations.',
    stock: 15,
    coverImage: '/images/national.png',
    publisher: 'W. W. Norton',
    isbn: '9780393317558',
    language: 'English',
    rating: 4.7,
    numReviews: 850,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
},
{
    _id: 'sample-16',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    price: 18.99,
    originalPrice: 24.99,
    discountPercent: 24,
    category: 'Science',
    description: 'An introduction to cosmology and black holes.',
    stock: 30,
    coverImage: '/images/stephen.png',
    publisher: 'Bantam Books',
    isbn: '9780553380163',
    language: 'English',
    rating: 4.8,
    numReviews: 3100,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
},
{
    _id: 'sample-17',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    price: 20.99,
    originalPrice: 26.99,
    discountPercent: 22,
    category: 'Science',
    description: 'A classic work on evolution and genetics.',
    stock: 17,
    coverImage: '/images/selfish.png',
    publisher: 'Oxford University Press',
    isbn: '9780199291151',
    language: 'English',
    rating: 4.7,
    numReviews: 920,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
}
];
