export const sampleCategories = [
  {
    name: 'Programming',
    slug: 'programming',
    description: 'Master web development, system architecture, algorithms & modern software engineering.',
    icon: '💻',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop',
    bookCount: 8
  },
  {
    name: 'Novels',
    slug: 'novels',
    description: 'Immerse yourself in world-class fiction, romance, thrillers, and award-winning literary works.',
    icon: '📖',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Academic',
    slug: 'academic',
    description: 'Essential textbooks, reference guides, research papers, and scholarly volumes.',
    icon: '🎓',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Children',
    slug: 'children',
    description: 'Delightful picture books, bed-time fairy tales, and engaging early reader adventures.',
    icon: '🎨',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Fantasy',
    slug: 'fantasy',
    description: 'Epic worlds, mythical creatures, high magic, and breathtaking heroic sagas.',
    icon: '🐉',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Biography',
    slug: 'biography',
    description: 'Inspiring life stories of visionaries, pioneers, leaders, and legendary figures.',
    icon: '👤',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'History',
    slug: 'history',
    description: 'Explore pivotal moments, ancient civilizations, world wars, and human heritage.',
    icon: '🏛️',
    image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop',
    bookCount: 4
  },
  {
    name: 'Science',
    slug: 'science',
    description: 'Discover quantum physics, astronomy, genetics, climate science, and nature.',
    icon: '🔬',
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop',
    bookCount: 5
  },
  {
    name: 'Self Help',
    slug: 'self-help',
    description: 'Actionable strategies for personal transformation, productivity, mindsets & success.',
    icon: '🌱',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop',
    bookCount: 6
  },
  {
    name: 'Mystery',
    slug: 'mystery',
    description: 'Gripping detective crime thrillers, unanswerable enigmas, and psychological suspense.',
    icon: '🔍',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop',
    bookCount: 5
  }
];

export const sampleBooks = [
  // Programming
  {
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    price: 39.99,
    originalPrice: 49.99,
    discountPercent: 20,
    category: 'Programming',
    description: 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn\'t have to be that way.',
    stock: 25,
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop',
    publisher: 'Prentice Hall',
    isbn: '978-0132350884',
    language: 'English',
    rating: 4.8,
    numReviews: 142,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    title: 'JavaScript: The Definitive Guide (7th Edition)',
    author: 'David Flanagan',
    price: 44.50,
    originalPrice: 59.99,
    discountPercent: 25,
    category: 'Programming',
    description: 'JavaScript is the programming language of the web and is used by more software developers than any other programming language. For nearly 25 years this best-seller has been the go-to guide for JavaScript programmers.',
    stock: 18,
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop',
    publisher: "O'Reilly Media",
    isbn: '978-1491952023',
    language: 'English',
    rating: 4.7,
    numReviews: 98,
    isFeatured: true,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    price: 49.99,
    originalPrice: 64.99,
    discountPercent: 23,
    category: 'Programming',
    description: 'Data is at the center of many challenges in system design today. Difficult issues such as scalability, consistency, reliability, efficiency, and maintainability need to be figured out. Martin Kleppmann helps you navigate this diverse landscape.',
    stock: 14,
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop',
    publisher: "O'Reilly Media",
    isbn: '978-1449373320',
    language: 'English',
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    title: 'Full Stack React Projects (Modern Web Apps)',
    author: 'Shama Hoque',
    price: 34.99,
    originalPrice: 42.00,
    discountPercent: 16,
    category: 'Programming',
    description: 'Build full-stack web applications with modern React, Express, Node.js, and MongoDB. Practical hands-on examples for real-world production projects.',
    stock: 30,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop',
    publisher: 'Packt Publishing',
    isbn: '978-1839215421',
    language: 'English',
    rating: 4.6,
    numReviews: 54,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: true
  },

  // Novels
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 14.99,
    originalPrice: 19.99,
    discountPercent: 25,
    category: 'Novels',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. Set in Jazz Age Long Island, it is a supreme classic of American literature.',
    stock: 40,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop',
    publisher: 'Scribner',
    isbn: '978-0743273565',
    language: 'English',
    rating: 4.6,
    numReviews: 320,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 16.50,
    originalPrice: 21.00,
    discountPercent: 21,
    category: 'Novels',
    description: 'Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty.',
    stock: 35,
    coverImage: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&auto=format&fit=crop',
    publisher: 'HarperPerennial',
    isbn: '978-0060935467',
    language: 'English',
    rating: 4.9,
    numReviews: 450,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },

  // Academic
  {
    title: 'Principles of Physics (11th Edition)',
    author: 'David Halliday & Robert Resnick',
    price: 89.99,
    originalPrice: 110.00,
    discountPercent: 18,
    category: 'Academic',
    description: 'The golden standard textbook for university physics. Covers mechanics, thermodynamics, electromagnetism, optics, and modern physics with problem sets.',
    stock: 12,
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop',
    publisher: 'Wiley',
    isbn: '978-1119454014',
    language: 'English',
    rating: 4.7,
    numReviews: 76,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: false
  },
  {
    title: 'Campbell Biology (12th Edition)',
    author: 'Lisa A. Urry',
    price: 95.00,
    originalPrice: 120.00,
    discountPercent: 20,
    category: 'Academic',
    description: 'The world\'s most successful biology textbook. Setting the standard for clarity, accuracy, and currency in biological sciences.',
    stock: 10,
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop',
    publisher: 'Pearson',
    isbn: '978-0135188743',
    language: 'English',
    rating: 4.8,
    numReviews: 89,
    isFeatured: true,
    isBestSeller: false,
    isTodayOffer: false
  },

  // Children
  {
    title: 'The Secret Garden & Magical Adventures',
    author: 'Frances Hodgson Burnett',
    price: 12.99,
    originalPrice: 15.99,
    discountPercent: 18,
    category: 'Children',
    description: 'An enchanting tale of young Mary Lennox who discovers a hidden, neglected garden and unlocks magic, friendship, and joy.',
    stock: 50,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop',
    publisher: 'Puffin Books',
    isbn: '978-0141321066',
    language: 'English',
    rating: 4.9,
    numReviews: 180,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },
  {
    title: 'Wonder & Curiosity: Young Explorers Guide',
    author: 'R. J. Palacio',
    price: 11.50,
    originalPrice: 14.00,
    discountPercent: 17,
    category: 'Children',
    description: 'Inspiring stories for kids celebrating kindness, empathy, friendship, and overcoming obstacles with courage.',
    stock: 22,
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop',
    publisher: 'Knopf Books for Young Readers',
    isbn: '978-0375869020',
    language: 'English',
    rating: 4.8,
    numReviews: 112,
    isFeatured: false,
    isBestSeller: false,
    isTodayOffer: false
  },

  // Fantasy
  {
    title: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    price: 22.99,
    originalPrice: 29.99,
    discountPercent: 23,
    category: 'Fantasy',
    description: 'The first volume in J.R.R. Tolkien\'s epic high fantasy masterpiece. Frodo Baggins embarks on a perilous journey to destroy the One Ring.',
    stock: 30,
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop',
    publisher: 'Houghton Mifflin Harcourt',
    isbn: '978-0547928210',
    language: 'English',
    rating: 4.9,
    numReviews: 620,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },

  // Biography
  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    price: 24.99,
    originalPrice: 32.00,
    discountPercent: 22,
    category: 'Biography',
    description: 'Based on more than forty interviews with Jobs conducted over two years, this is the riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur.',
    stock: 20,
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop',
    publisher: 'Simon & Schuster',
    isbn: '978-1451648539',
    language: 'English',
    rating: 4.8,
    numReviews: 310,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  },

  // History
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    price: 21.99,
    originalPrice: 28.00,
    discountPercent: 21,
    category: 'History',
    description: '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance?',
    stock: 35,
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop',
    publisher: 'Harper',
    isbn: '978-0062316097',
    language: 'English',
    rating: 4.8,
    numReviews: 540,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },

  // Science
  {
    title: 'Astrophysics for People in a Hurry',
    author: 'Neil deGrasse Tyson',
    price: 18.50,
    originalPrice: 22.99,
    discountPercent: 19,
    category: 'Science',
    description: 'What is the nature of space and time? How do we fit within the universe? Neil deGrasse Tyson brings the universe down to Earth succinctly and clearly.',
    stock: 28,
    coverImage: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop',
    publisher: 'W. W. Norton & Company',
    isbn: '978-0393609394',
    language: 'English',
    rating: 4.7,
    numReviews: 240,
    isFeatured: true,
    isBestSeller: false,
    isTodayOffer: false
  },

  // Self Help
  {
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits',
    author: 'James Clear',
    price: 19.99,
    originalPrice: 27.00,
    discountPercent: 26,
    category: 'Self Help',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master small behaviors.',
    stock: 45,
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop',
    publisher: 'Avery',
    isbn: '978-0735211292',
    language: 'English',
    rating: 4.9,
    numReviews: 890,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: true
  },

  // Mystery
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 17.99,
    originalPrice: 24.99,
    discountPercent: 28,
    category: 'Mystery',
    description: 'Alicia Berenson\'s life is seemingly perfect. Then one evening her husband returns home late from a fashion shoot, and Alicia shoots him five times in the face and never speaks another word.',
    stock: 25,
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop',
    publisher: 'Celadon Books',
    isbn: '978-1250301697',
    language: 'English',
    rating: 4.7,
    numReviews: 380,
    isFeatured: true,
    isBestSeller: true,
    isTodayOffer: false
  }
];
